-- Generated by tools/generate-quiz-seed.mjs from js/data/quiz-data.js
USE adb_learning_platform;

INSERT INTO quiz_questions (topic_id, question_text, option_a, option_b, option_c, option_d, correct_option, explanation, question_type)
SELECT t.topic_id, 'Which statement creates a new database?', 'CREATE DATABASE', 'MAKE DATABASE', 'NEW DATABASE', 'ADD DATABASE', 'A', NULL, 'mcq' FROM topics t WHERE t.topic_code = 'create-db' AND NOT EXISTS (
  SELECT 1 FROM quiz_questions q WHERE q.topic_id = t.topic_id AND q.question_text = 'Which statement creates a new database?'
);

INSERT INTO quiz_questions (topic_id, question_text, option_a, option_b, option_c, option_d, correct_option, explanation, question_type)
SELECT t.topic_id, 'What does the USE statement do?', 'Selects a database to work with', 'Creates a new user', 'Updates the database schema', 'Deletes the database', 'A', NULL, 'mcq' FROM topics t WHERE t.topic_code = 'create-db' AND NOT EXISTS (
  SELECT 1 FROM quiz_questions q WHERE q.topic_id = t.topic_id AND q.question_text = 'What does the USE statement do?'
);

INSERT INTO quiz_questions (topic_id, question_text, option_a, option_b, option_c, option_d, correct_option, explanation, question_type)
SELECT t.topic_id, 'What does IF NOT EXISTS do in CREATE DATABASE?', 'Prevents an error if the database already exists', 'Deletes the existing database', 'Updates the existing database', 'Renames the existing database', 'A', NULL, 'mcq' FROM topics t WHERE t.topic_code = 'create-db' AND NOT EXISTS (
  SELECT 1 FROM quiz_questions q WHERE q.topic_id = t.topic_id AND q.question_text = 'What does IF NOT EXISTS do in CREATE DATABASE?'
);

INSERT INTO quiz_questions (topic_id, question_text, option_a, option_b, option_c, option_d, correct_option, explanation, question_type)
SELECT t.topic_id, 'Which constraint ensures a column cannot have NULL values?', 'NOT NULL', 'NO EMPTY', 'REQUIRED', 'MANDATORY', 'A', NULL, 'mcq' FROM topics t WHERE t.topic_code = 'create-table' AND NOT EXISTS (
  SELECT 1 FROM quiz_questions q WHERE q.topic_id = t.topic_id AND q.question_text = 'Which constraint ensures a column cannot have NULL values?'
);

INSERT INTO quiz_questions (topic_id, question_text, option_a, option_b, option_c, option_d, correct_option, explanation, question_type)
SELECT t.topic_id, 'What is AUTO_INCREMENT used for?', 'Automatically generating unique ID values', 'Increasing the table size automatically', 'Adding more columns automatically', 'Automatically deleting old records', 'A', NULL, 'mcq' FROM topics t WHERE t.topic_code = 'create-table' AND NOT EXISTS (
  SELECT 1 FROM quiz_questions q WHERE q.topic_id = t.topic_id AND q.question_text = 'What is AUTO_INCREMENT used for?'
);

INSERT INTO quiz_questions (topic_id, question_text, option_a, option_b, option_c, option_d, correct_option, explanation, question_type)
SELECT t.topic_id, 'What is the purpose of a FOREIGN KEY?', 'To create a relationship between two tables', 'To make a column unique', 'To prevent NULL values', 'To automatically delete records', 'A', NULL, 'mcq' FROM topics t WHERE t.topic_code = 'create-table' AND NOT EXISTS (
  SELECT 1 FROM quiz_questions q WHERE q.topic_id = t.topic_id AND q.question_text = 'What is the purpose of a FOREIGN KEY?'
);

INSERT INTO quiz_questions (topic_id, question_text, option_a, option_b, option_c, option_d, correct_option, explanation, question_type)
SELECT t.topic_id, 'Which data type is best for storing prices with exact precision?', 'DECIMAL', 'FLOAT', 'DOUBLE', 'INT', 'A', NULL, 'mcq' FROM topics t WHERE t.topic_code = 'data-types' AND NOT EXISTS (
  SELECT 1 FROM quiz_questions q WHERE q.topic_id = t.topic_id AND q.question_text = 'Which data type is best for storing prices with exact precision?'
);

INSERT INTO quiz_questions (topic_id, question_text, option_a, option_b, option_c, option_d, correct_option, explanation, question_type)
SELECT t.topic_id, 'What is the difference between CHAR and VARCHAR?', 'CHAR has fixed length, VARCHAR has variable length', 'CHAR is for numbers, VARCHAR is for text', 'CHAR can store more characters', 'There is no difference', 'A', NULL, 'mcq' FROM topics t WHERE t.topic_code = 'data-types' AND NOT EXISTS (
  SELECT 1 FROM quiz_questions q WHERE q.topic_id = t.topic_id AND q.question_text = 'What is the difference between CHAR and VARCHAR?'
);

INSERT INTO quiz_questions (topic_id, question_text, option_a, option_b, option_c, option_d, correct_option, explanation, question_type)
SELECT t.topic_id, 'Which data type stores both date and time?', 'DATETIME', 'DATE', 'TIME', 'YEAR', 'A', NULL, 'mcq' FROM topics t WHERE t.topic_code = 'data-types' AND NOT EXISTS (
  SELECT 1 FROM quiz_questions q WHERE q.topic_id = t.topic_id AND q.question_text = 'Which data type stores both date and time?'
);

INSERT INTO quiz_questions (topic_id, question_text, option_a, option_b, option_c, option_d, correct_option, explanation, question_type)
SELECT t.topic_id, 'What does SELECT * do?', 'Returns all columns from a table', 'Returns only the first row', 'Returns only numeric columns', 'Deletes all data', 'A', NULL, 'mcq' FROM topics t WHERE t.topic_code = 'select' AND NOT EXISTS (
  SELECT 1 FROM quiz_questions q WHERE q.topic_id = t.topic_id AND q.question_text = 'What does SELECT * do?'
);

INSERT INTO quiz_questions (topic_id, question_text, option_a, option_b, option_c, option_d, correct_option, explanation, question_type)
SELECT t.topic_id, 'What does the AS keyword do?', 'Creates an alias (alternate name) for a column', 'Adds two columns together', 'Sorts the results', 'Filters the data', 'A', NULL, 'mcq' FROM topics t WHERE t.topic_code = 'select' AND NOT EXISTS (
  SELECT 1 FROM quiz_questions q WHERE q.topic_id = t.topic_id AND q.question_text = 'What does the AS keyword do?'
);

INSERT INTO quiz_questions (topic_id, question_text, option_a, option_b, option_c, option_d, correct_option, explanation, question_type)
SELECT t.topic_id, 'What does DISTINCT do?', 'Returns only unique values, removing duplicates', 'Sorts results in descending order', 'Limits results to 10 rows', 'Joins two tables', 'A', NULL, 'mcq' FROM topics t WHERE t.topic_code = 'select' AND NOT EXISTS (
  SELECT 1 FROM quiz_questions q WHERE q.topic_id = t.topic_id AND q.question_text = 'What does DISTINCT do?'
);

INSERT INTO quiz_questions (topic_id, question_text, option_a, option_b, option_c, option_d, correct_option, explanation, question_type)
SELECT t.topic_id, 'What is the purpose of the WHERE clause?', 'To filter rows based on conditions', 'To sort the results', 'To group data', 'To join tables', 'A', NULL, 'mcq' FROM topics t WHERE t.topic_code = 'where' AND NOT EXISTS (
  SELECT 1 FROM quiz_questions q WHERE q.topic_id = t.topic_id AND q.question_text = 'What is the purpose of the WHERE clause?'
);

INSERT INTO quiz_questions (topic_id, question_text, option_a, option_b, option_c, option_d, correct_option, explanation, question_type)
SELECT t.topic_id, 'Which operator means "not equal to" in SQL?', '<> or !=', '=', '><', '!!', 'A', NULL, 'mcq' FROM topics t WHERE t.topic_code = 'where' AND NOT EXISTS (
  SELECT 1 FROM quiz_questions q WHERE q.topic_id = t.topic_id AND q.question_text = 'Which operator means "not equal to" in SQL?'
);

INSERT INTO quiz_questions (topic_id, question_text, option_a, option_b, option_c, option_d, correct_option, explanation, question_type)
SELECT t.topic_id, 'What does the LIKE operator do?', 'Pattern matching for strings', 'Adds two numbers', 'Sorts alphabetically', 'Counts rows', 'A', NULL, 'mcq' FROM topics t WHERE t.topic_code = 'where' AND NOT EXISTS (
  SELECT 1 FROM quiz_questions q WHERE q.topic_id = t.topic_id AND q.question_text = 'What does the LIKE operator do?'
);

INSERT INTO quiz_questions (topic_id, question_text, option_a, option_b, option_c, option_d, correct_option, explanation, question_type)
SELECT t.topic_id, 'Which statement adds new data to a table?', 'INSERT INTO', 'ADD DATA', 'NEW RECORD', 'CREATE ROW', 'A', NULL, 'mcq' FROM topics t WHERE t.topic_code = 'insert' AND NOT EXISTS (
  SELECT 1 FROM quiz_questions q WHERE q.topic_id = t.topic_id AND q.question_text = 'Which statement adds new data to a table?'
);

INSERT INTO quiz_questions (topic_id, question_text, option_a, option_b, option_c, option_d, correct_option, explanation, question_type)
SELECT t.topic_id, 'Can you insert multiple rows in a single INSERT statement?', 'Yes, by separating row values with commas', 'No, only one row at a time', 'Only with a special permission', 'Only in Oracle databases', 'A', NULL, 'mcq' FROM topics t WHERE t.topic_code = 'insert' AND NOT EXISTS (
  SELECT 1 FROM quiz_questions q WHERE q.topic_id = t.topic_id AND q.question_text = 'Can you insert multiple rows in a single INSERT statement?'
);

INSERT INTO quiz_questions (topic_id, question_text, option_a, option_b, option_c, option_d, correct_option, explanation, question_type)
SELECT t.topic_id, 'What happens if you omit a NOT NULL column in INSERT?', 'An error occurs', 'NULL is inserted', 'The row is skipped', 'A random value is generated', 'A', NULL, 'mcq' FROM topics t WHERE t.topic_code = 'insert' AND NOT EXISTS (
  SELECT 1 FROM quiz_questions q WHERE q.topic_id = t.topic_id AND q.question_text = 'What happens if you omit a NOT NULL column in INSERT?'
);

INSERT INTO quiz_questions (topic_id, question_text, option_a, option_b, option_c, option_d, correct_option, explanation, question_type)
SELECT t.topic_id, 'What happens if you run UPDATE without WHERE?', 'All rows in the table are updated', 'Only the first row is updated', 'An error occurs', 'Nothing happens', 'A', NULL, 'mcq' FROM topics t WHERE t.topic_code = 'update' AND NOT EXISTS (
  SELECT 1 FROM quiz_questions q WHERE q.topic_id = t.topic_id AND q.question_text = 'What happens if you run UPDATE without WHERE?'
);

INSERT INTO quiz_questions (topic_id, question_text, option_a, option_b, option_c, option_d, correct_option, explanation, question_type)
SELECT t.topic_id, 'Can UPDATE change multiple columns at once?', 'Yes, separate columns with commas', 'No, one column at a time', 'Only in Oracle', 'Only with a stored procedure', 'A', NULL, 'mcq' FROM topics t WHERE t.topic_code = 'update' AND NOT EXISTS (
  SELECT 1 FROM quiz_questions q WHERE q.topic_id = t.topic_id AND q.question_text = 'Can UPDATE change multiple columns at once?'
);

INSERT INTO quiz_questions (topic_id, question_text, option_a, option_b, option_c, option_d, correct_option, explanation, question_type)
SELECT t.topic_id, 'What is the correct order for UPDATE syntax?', 'UPDATE table SET column=value WHERE condition', 'UPDATE SET table.column=value WHERE condition', 'SET UPDATE table column=value WHERE condition', 'UPDATE WHERE condition SET table.column=value', 'A', NULL, 'mcq' FROM topics t WHERE t.topic_code = 'update' AND NOT EXISTS (
  SELECT 1 FROM quiz_questions q WHERE q.topic_id = t.topic_id AND q.question_text = 'What is the correct order for UPDATE syntax?'
);

INSERT INTO quiz_questions (topic_id, question_text, option_a, option_b, option_c, option_d, correct_option, explanation, question_type)
SELECT t.topic_id, 'What happens if you run DELETE without WHERE?', 'All rows are permanently deleted', 'Only the first row is deleted', 'The table is dropped', 'Nothing happens', 'A', NULL, 'mcq' FROM topics t WHERE t.topic_code = 'delete' AND NOT EXISTS (
  SELECT 1 FROM quiz_questions q WHERE q.topic_id = t.topic_id AND q.question_text = 'What happens if you run DELETE without WHERE?'
);

INSERT INTO quiz_questions (topic_id, question_text, option_a, option_b, option_c, option_d, correct_option, explanation, question_type)
SELECT t.topic_id, 'What is the difference between DELETE and TRUNCATE?', 'TRUNCATE is faster but cannot use WHERE', 'There is no difference', 'DELETE is faster', 'TRUNCATE only deletes the first row', 'A', NULL, 'mcq' FROM topics t WHERE t.topic_code = 'delete' AND NOT EXISTS (
  SELECT 1 FROM quiz_questions q WHERE q.topic_id = t.topic_id AND q.question_text = 'What is the difference between DELETE and TRUNCATE?'
);

INSERT INTO quiz_questions (topic_id, question_text, option_a, option_b, option_c, option_d, correct_option, explanation, question_type)
SELECT t.topic_id, 'Is DELETE reversible?', 'No, unless you have a backup or transaction rollback', 'Yes, with UNDO command', 'Yes, it moves data to recycle bin', 'Yes, automatically after 24 hours', 'A', NULL, 'mcq' FROM topics t WHERE t.topic_code = 'delete' AND NOT EXISTS (
  SELECT 1 FROM quiz_questions q WHERE q.topic_id = t.topic_id AND q.question_text = 'Is DELETE reversible?'
);

INSERT INTO quiz_questions (topic_id, question_text, option_a, option_b, option_c, option_d, correct_option, explanation, question_type)
SELECT t.topic_id, 'What does INNER JOIN return?', 'Only rows that have matching values in both tables', 'All rows from the left table', 'All rows from both tables', 'Only rows that don''t match', 'A', NULL, 'mcq' FROM topics t WHERE t.topic_code = 'joins' AND NOT EXISTS (
  SELECT 1 FROM quiz_questions q WHERE q.topic_id = t.topic_id AND q.question_text = 'What does INNER JOIN return?'
);

INSERT INTO quiz_questions (topic_id, question_text, option_a, option_b, option_c, option_d, correct_option, explanation, question_type)
SELECT t.topic_id, 'What does LEFT JOIN return?', 'All rows from the left table, plus matching rows from the right', 'Only matching rows from both', 'All rows from the right table', 'Rows that don''t match', 'A', NULL, 'mcq' FROM topics t WHERE t.topic_code = 'joins' AND NOT EXISTS (
  SELECT 1 FROM quiz_questions q WHERE q.topic_id = t.topic_id AND q.question_text = 'What does LEFT JOIN return?'
);

INSERT INTO quiz_questions (topic_id, question_text, option_a, option_b, option_c, option_d, correct_option, explanation, question_type)
SELECT t.topic_id, 'What is required for a JOIN condition?', 'A common column between the tables', 'The tables must have the same name', 'The tables must have the same number of rows', 'Both tables must be empty', 'A', NULL, 'mcq' FROM topics t WHERE t.topic_code = 'joins' AND NOT EXISTS (
  SELECT 1 FROM quiz_questions q WHERE q.topic_id = t.topic_id AND q.question_text = 'What is required for a JOIN condition?'
);

INSERT INTO quiz_questions (topic_id, question_text, option_a, option_b, option_c, option_d, correct_option, explanation, question_type)
SELECT t.topic_id, 'What does COUNT(*) return?', 'The total number of rows', 'The sum of all values', 'The average of all values', 'The highest value', 'A', NULL, 'mcq' FROM topics t WHERE t.topic_code = 'aggregate' AND NOT EXISTS (
  SELECT 1 FROM quiz_questions q WHERE q.topic_id = t.topic_id AND q.question_text = 'What does COUNT(*) return?'
);

INSERT INTO quiz_questions (topic_id, question_text, option_a, option_b, option_c, option_d, correct_option, explanation, question_type)
SELECT t.topic_id, 'Which function calculates the average?', 'AVG()', 'MEAN()', 'AVERAGE()', 'MEDIAN()', 'A', NULL, 'mcq' FROM topics t WHERE t.topic_code = 'aggregate' AND NOT EXISTS (
  SELECT 1 FROM quiz_questions q WHERE q.topic_id = t.topic_id AND q.question_text = 'Which function calculates the average?'
);

INSERT INTO quiz_questions (topic_id, question_text, option_a, option_b, option_c, option_d, correct_option, explanation, question_type)
SELECT t.topic_id, 'What happens to NULL values in aggregate functions?', 'They are ignored (except in COUNT(*))', 'They are counted as 0', 'They cause an error', 'They are counted as 1', 'A', NULL, 'mcq' FROM topics t WHERE t.topic_code = 'aggregate' AND NOT EXISTS (
  SELECT 1 FROM quiz_questions q WHERE q.topic_id = t.topic_id AND q.question_text = 'What happens to NULL values in aggregate functions?'
);

INSERT INTO quiz_questions (topic_id, question_text, option_a, option_b, option_c, option_d, correct_option, explanation, question_type)
SELECT t.topic_id, 'What does GROUP BY do?', 'Groups rows with the same values into summary rows', 'Sorts the results alphabetically', 'Filters rows based on a condition', 'Joins multiple tables', 'A', NULL, 'mcq' FROM topics t WHERE t.topic_code = 'group-by' AND NOT EXISTS (
  SELECT 1 FROM quiz_questions q WHERE q.topic_id = t.topic_id AND q.question_text = 'What does GROUP BY do?'
);

INSERT INTO quiz_questions (topic_id, question_text, option_a, option_b, option_c, option_d, correct_option, explanation, question_type)
SELECT t.topic_id, 'What is the difference between WHERE and HAVING?', 'WHERE filters rows before grouping, HAVING filters after', 'There is no difference', 'WHERE is faster', 'HAVING can only be used with COUNT', 'A', NULL, 'mcq' FROM topics t WHERE t.topic_code = 'group-by' AND NOT EXISTS (
  SELECT 1 FROM quiz_questions q WHERE q.topic_id = t.topic_id AND q.question_text = 'What is the difference between WHERE and HAVING?'
);

INSERT INTO quiz_questions (topic_id, question_text, option_a, option_b, option_c, option_d, correct_option, explanation, question_type)
SELECT t.topic_id, 'Can you use regular columns with aggregate functions without GROUP BY?', 'No, you must GROUP BY all non-aggregated columns', 'Yes, always', 'Only in MySQL', 'Only with COUNT', 'A', NULL, 'mcq' FROM topics t WHERE t.topic_code = 'group-by' AND NOT EXISTS (
  SELECT 1 FROM quiz_questions q WHERE q.topic_id = t.topic_id AND q.question_text = 'Can you use regular columns with aggregate functions without GROUP BY?'
);

INSERT INTO quiz_questions (topic_id, question_text, option_a, option_b, option_c, option_d, correct_option, explanation, question_type)
SELECT t.topic_id, 'What is a subquery?', 'A query inside another query', 'A query that runs faster', 'A query with no results', 'A query that deletes data', 'A', NULL, 'mcq' FROM topics t WHERE t.topic_code = 'subqueries' AND NOT EXISTS (
  SELECT 1 FROM quiz_questions q WHERE q.topic_id = t.topic_id AND q.question_text = 'What is a subquery?'
);

INSERT INTO quiz_questions (topic_id, question_text, option_a, option_b, option_c, option_d, correct_option, explanation, question_type)
SELECT t.topic_id, 'Where can subqueries be used?', 'In SELECT, FROM, WHERE, and HAVING clauses', 'Only in WHERE clause', 'Only in SELECT clause', 'Only in FROM clause', 'A', NULL, 'mcq' FROM topics t WHERE t.topic_code = 'subqueries' AND NOT EXISTS (
  SELECT 1 FROM quiz_questions q WHERE q.topic_id = t.topic_id AND q.question_text = 'Where can subqueries be used?'
);

INSERT INTO quiz_questions (topic_id, question_text, option_a, option_b, option_c, option_d, correct_option, explanation, question_type)
SELECT t.topic_id, 'Which operator is used with multi-row subqueries?', 'IN', '=', '+', '>', 'A', NULL, 'mcq' FROM topics t WHERE t.topic_code = 'subqueries' AND NOT EXISTS (
  SELECT 1 FROM quiz_questions q WHERE q.topic_id = t.topic_id AND q.question_text = 'Which operator is used with multi-row subqueries?'
);

INSERT INTO quiz_questions (topic_id, question_text, option_a, option_b, option_c, option_d, correct_option, explanation, question_type)
SELECT t.topic_id, 'What is the main purpose of an index?', 'To speed up data retrieval', 'To store more data', 'To encrypt the database', 'To delete old records', 'A', NULL, 'mcq' FROM topics t WHERE t.topic_code = 'indexes' AND NOT EXISTS (
  SELECT 1 FROM quiz_questions q WHERE q.topic_id = t.topic_id AND q.question_text = 'What is the main purpose of an index?'
);

INSERT INTO quiz_questions (topic_id, question_text, option_a, option_b, option_c, option_d, correct_option, explanation, question_type)
SELECT t.topic_id, 'What is the trade-off of using indexes?', 'Faster reads but slower writes and more storage', 'Slower reads but faster writes', 'No trade-off, only benefits', 'Less storage but slower everything', 'A', NULL, 'mcq' FROM topics t WHERE t.topic_code = 'indexes' AND NOT EXISTS (
  SELECT 1 FROM quiz_questions q WHERE q.topic_id = t.topic_id AND q.question_text = 'What is the trade-off of using indexes?'
);

INSERT INTO quiz_questions (topic_id, question_text, option_a, option_b, option_c, option_d, correct_option, explanation, question_type)
SELECT t.topic_id, 'Are primary keys automatically indexed?', 'Yes', 'No', 'Only in Oracle', 'Only in MySQL', 'A', NULL, 'mcq' FROM topics t WHERE t.topic_code = 'indexes' AND NOT EXISTS (
  SELECT 1 FROM quiz_questions q WHERE q.topic_id = t.topic_id AND q.question_text = 'Are primary keys automatically indexed?'
);

INSERT INTO quiz_questions (topic_id, question_text, option_a, option_b, option_c, option_d, correct_option, explanation, question_type)
SELECT t.topic_id, 'What is MySQL?', 'An open-source relational database management system', 'A programming language', 'A web server', 'An operating system', 'A', NULL, 'mcq' FROM topics t WHERE t.topic_code = 'mysql-intro' AND NOT EXISTS (
  SELECT 1 FROM quiz_questions q WHERE q.topic_id = t.topic_id AND q.question_text = 'What is MySQL?'
);

INSERT INTO quiz_questions (topic_id, question_text, option_a, option_b, option_c, option_d, correct_option, explanation, question_type)
SELECT t.topic_id, 'Which companies use MySQL?', 'Facebook, Twitter, YouTube, Wikipedia', 'Only small websites', 'Only banking systems', 'Only mobile apps', 'A', NULL, 'mcq' FROM topics t WHERE t.topic_code = 'mysql-intro' AND NOT EXISTS (
  SELECT 1 FROM quiz_questions q WHERE q.topic_id = t.topic_id AND q.question_text = 'Which companies use MySQL?'
);

INSERT INTO quiz_questions (topic_id, question_text, option_a, option_b, option_c, option_d, correct_option, explanation, question_type)
SELECT t.topic_id, 'What does RDBMS stand for?', 'Relational Database Management System', 'Random Data Base Management Software', 'Relational Data Building and Management System', 'Real Database Management Solution', 'A', NULL, 'mcq' FROM topics t WHERE t.topic_code = 'mysql-intro' AND NOT EXISTS (
  SELECT 1 FROM quiz_questions q WHERE q.topic_id = t.topic_id AND q.question_text = 'What does RDBMS stand for?'
);

INSERT INTO quiz_questions (topic_id, question_text, option_a, option_b, option_c, option_d, correct_option, explanation, question_type)
SELECT t.topic_id, 'What is a table in RDBMS?', 'A collection of related data entries organized in rows and columns', 'A piece of furniture', 'A type of chart', 'A database user', 'A', NULL, 'mcq' FROM topics t WHERE t.topic_code = 'mysql-rdbms' AND NOT EXISTS (
  SELECT 1 FROM quiz_questions q WHERE q.topic_id = t.topic_id AND q.question_text = 'What is a table in RDBMS?'
);

INSERT INTO quiz_questions (topic_id, question_text, option_a, option_b, option_c, option_d, correct_option, explanation, question_type)
SELECT t.topic_id, 'What is a Primary Key?', 'A unique identifier for each row in a table', 'The main password for the database', 'The first column in every table', 'The most important data in the table', 'A', NULL, 'mcq' FROM topics t WHERE t.topic_code = 'mysql-rdbms' AND NOT EXISTS (
  SELECT 1 FROM quiz_questions q WHERE q.topic_id = t.topic_id AND q.question_text = 'What is a Primary Key?'
);

INSERT INTO quiz_questions (topic_id, question_text, option_a, option_b, option_c, option_d, correct_option, explanation, question_type)
SELECT t.topic_id, 'What does SQL stand for?', 'Structured Query Language', 'Simple Question Language', 'System Query Logic', 'Structured Question Link', 'A', NULL, 'mcq' FROM topics t WHERE t.topic_code = 'mysql-sql' AND NOT EXISTS (
  SELECT 1 FROM quiz_questions q WHERE q.topic_id = t.topic_id AND q.question_text = 'What does SQL stand for?'
);

INSERT INTO quiz_questions (topic_id, question_text, option_a, option_b, option_c, option_d, correct_option, explanation, question_type)
SELECT t.topic_id, 'Is SQL case-sensitive?', 'No, SQL keywords are not case-sensitive', 'Yes, everything must be in UPPERCASE', 'Yes, everything must be in lowercase', 'Only table names are case-sensitive', 'A', NULL, 'mcq' FROM topics t WHERE t.topic_code = 'mysql-sql' AND NOT EXISTS (
  SELECT 1 FROM quiz_questions q WHERE q.topic_id = t.topic_id AND q.question_text = 'Is SQL case-sensitive?'
);

INSERT INTO quiz_questions (topic_id, question_text, option_a, option_b, option_c, option_d, correct_option, explanation, question_type)
SELECT t.topic_id, 'What does SELECT * do?', 'Returns all columns from a table', 'Returns only the first row', 'Returns only numeric columns', 'Deletes all data', 'A', NULL, 'mcq' FROM topics t WHERE t.topic_code = 'mysql-select' AND NOT EXISTS (
  SELECT 1 FROM quiz_questions q WHERE q.topic_id = t.topic_id AND q.question_text = 'What does SELECT * do?'
);

INSERT INTO quiz_questions (topic_id, question_text, option_a, option_b, option_c, option_d, correct_option, explanation, question_type)
SELECT t.topic_id, 'What does the AS keyword do?', 'Creates an alias (alternate name) for a column', 'Adds two columns together', 'Sorts the results', 'Filters the data', 'A', NULL, 'mcq' FROM topics t WHERE t.topic_code = 'mysql-select' AND NOT EXISTS (
  SELECT 1 FROM quiz_questions q WHERE q.topic_id = t.topic_id AND q.question_text = 'What does the AS keyword do?'
);

INSERT INTO quiz_questions (topic_id, question_text, option_a, option_b, option_c, option_d, correct_option, explanation, question_type)
SELECT t.topic_id, 'What does DISTINCT do?', 'Returns only unique values, removing duplicates', 'Sorts results in descending order', 'Limits results to 10 rows', 'Joins two tables', 'A', NULL, 'mcq' FROM topics t WHERE t.topic_code = 'mysql-select-distinct' AND NOT EXISTS (
  SELECT 1 FROM quiz_questions q WHERE q.topic_id = t.topic_id AND q.question_text = 'What does DISTINCT do?'
);

INSERT INTO quiz_questions (topic_id, question_text, option_a, option_b, option_c, option_d, correct_option, explanation, question_type)
SELECT t.topic_id, 'What is the purpose of the WHERE clause?', 'To filter rows based on conditions', 'To sort the results', 'To group data', 'To join tables', 'A', NULL, 'mcq' FROM topics t WHERE t.topic_code = 'mysql-where' AND NOT EXISTS (
  SELECT 1 FROM quiz_questions q WHERE q.topic_id = t.topic_id AND q.question_text = 'What is the purpose of the WHERE clause?'
);

INSERT INTO quiz_questions (topic_id, question_text, option_a, option_b, option_c, option_d, correct_option, explanation, question_type)
SELECT t.topic_id, 'Which operator means "not equal to" in SQL?', '<> or !=', '=', '><', '!!', 'A', NULL, 'mcq' FROM topics t WHERE t.topic_code = 'mysql-where' AND NOT EXISTS (
  SELECT 1 FROM quiz_questions q WHERE q.topic_id = t.topic_id AND q.question_text = 'Which operator means "not equal to" in SQL?'
);

INSERT INTO quiz_questions (topic_id, question_text, option_a, option_b, option_c, option_d, correct_option, explanation, question_type)
SELECT t.topic_id, 'What does the AND operator do?', 'Requires both conditions to be true', 'Requires either condition to be true', 'Negates a condition', 'Sorts the results', 'A', NULL, 'mcq' FROM topics t WHERE t.topic_code = 'mysql-and' AND NOT EXISTS (
  SELECT 1 FROM quiz_questions q WHERE q.topic_id = t.topic_id AND q.question_text = 'What does the AND operator do?'
);

INSERT INTO quiz_questions (topic_id, question_text, option_a, option_b, option_c, option_d, correct_option, explanation, question_type)
SELECT t.topic_id, 'What does the OR operator do?', 'Requires either condition to be true', 'Requires both conditions to be true', 'Negates a condition', 'Limits the results', 'A', NULL, 'mcq' FROM topics t WHERE t.topic_code = 'mysql-or' AND NOT EXISTS (
  SELECT 1 FROM quiz_questions q WHERE q.topic_id = t.topic_id AND q.question_text = 'What does the OR operator do?'
);

INSERT INTO quiz_questions (topic_id, question_text, option_a, option_b, option_c, option_d, correct_option, explanation, question_type)
SELECT t.topic_id, 'What does the NOT operator do?', 'Negates a condition (opposite of the condition)', 'Adds two conditions together', 'Sorts in reverse order', 'Deletes records', 'A', NULL, 'mcq' FROM topics t WHERE t.topic_code = 'mysql-not' AND NOT EXISTS (
  SELECT 1 FROM quiz_questions q WHERE q.topic_id = t.topic_id AND q.question_text = 'What does the NOT operator do?'
);

INSERT INTO quiz_questions (topic_id, question_text, option_a, option_b, option_c, option_d, correct_option, explanation, question_type)
SELECT t.topic_id, 'What does ORDER BY do?', 'Sorts the result set', 'Filters rows', 'Groups data', 'Joins tables', 'A', NULL, 'mcq' FROM topics t WHERE t.topic_code = 'mysql-order-by' AND NOT EXISTS (
  SELECT 1 FROM quiz_questions q WHERE q.topic_id = t.topic_id AND q.question_text = 'What does ORDER BY do?'
);

INSERT INTO quiz_questions (topic_id, question_text, option_a, option_b, option_c, option_d, correct_option, explanation, question_type)
SELECT t.topic_id, 'What is the default sort order?', 'Ascending (ASC)', 'Descending (DESC)', 'Random', 'Alphabetical', 'A', NULL, 'mcq' FROM topics t WHERE t.topic_code = 'mysql-order-by' AND NOT EXISTS (
  SELECT 1 FROM quiz_questions q WHERE q.topic_id = t.topic_id AND q.question_text = 'What is the default sort order?'
);

INSERT INTO quiz_questions (topic_id, question_text, option_a, option_b, option_c, option_d, correct_option, explanation, question_type)
SELECT t.topic_id, 'Which statement adds new data to a table?', 'INSERT INTO', 'ADD DATA', 'NEW RECORD', 'CREATE ROW', 'A', NULL, 'mcq' FROM topics t WHERE t.topic_code = 'mysql-insert' AND NOT EXISTS (
  SELECT 1 FROM quiz_questions q WHERE q.topic_id = t.topic_id AND q.question_text = 'Which statement adds new data to a table?'
);

INSERT INTO quiz_questions (topic_id, question_text, option_a, option_b, option_c, option_d, correct_option, explanation, question_type)
SELECT t.topic_id, 'What does NULL represent?', 'A missing or unknown value', 'Zero', 'An empty string', 'False', 'A', NULL, 'mcq' FROM topics t WHERE t.topic_code = 'mysql-null' AND NOT EXISTS (
  SELECT 1 FROM quiz_questions q WHERE q.topic_id = t.topic_id AND q.question_text = 'What does NULL represent?'
);

INSERT INTO quiz_questions (topic_id, question_text, option_a, option_b, option_c, option_d, correct_option, explanation, question_type)
SELECT t.topic_id, 'What happens if you run UPDATE without WHERE?', 'All rows in the table are updated', 'Only the first row is updated', 'An error occurs', 'Nothing happens', 'A', NULL, 'mcq' FROM topics t WHERE t.topic_code = 'mysql-update' AND NOT EXISTS (
  SELECT 1 FROM quiz_questions q WHERE q.topic_id = t.topic_id AND q.question_text = 'What happens if you run UPDATE without WHERE?'
);

INSERT INTO quiz_questions (topic_id, question_text, option_a, option_b, option_c, option_d, correct_option, explanation, question_type)
SELECT t.topic_id, 'What happens if you run DELETE without WHERE?', 'All rows are permanently deleted', 'Only the first row is deleted', 'The table is dropped', 'Nothing happens', 'A', NULL, 'mcq' FROM topics t WHERE t.topic_code = 'mysql-delete' AND NOT EXISTS (
  SELECT 1 FROM quiz_questions q WHERE q.topic_id = t.topic_id AND q.question_text = 'What happens if you run DELETE without WHERE?'
);

INSERT INTO quiz_questions (topic_id, question_text, option_a, option_b, option_c, option_d, correct_option, explanation, question_type)
SELECT t.topic_id, 'What does LIMIT do?', 'Limits the number of records returned', 'Limits column values', 'Limits table size', 'Limits database connections', 'A', NULL, 'mcq' FROM topics t WHERE t.topic_code = 'mysql-limit' AND NOT EXISTS (
  SELECT 1 FROM quiz_questions q WHERE q.topic_id = t.topic_id AND q.question_text = 'What does LIMIT do?'
);

INSERT INTO quiz_questions (topic_id, question_text, option_a, option_b, option_c, option_d, correct_option, explanation, question_type)
SELECT t.topic_id, 'What does MIN() return?', 'The smallest value in a column', 'The largest value in a column', 'The average value', 'The total count', 'A', NULL, 'mcq' FROM topics t WHERE t.topic_code = 'mysql-min-max' AND NOT EXISTS (
  SELECT 1 FROM quiz_questions q WHERE q.topic_id = t.topic_id AND q.question_text = 'What does MIN() return?'
);

INSERT INTO quiz_questions (topic_id, question_text, option_a, option_b, option_c, option_d, correct_option, explanation, question_type)
SELECT t.topic_id, 'What does MAX() return?', 'The largest value in a column', 'The smallest value in a column', 'The average value', 'The total count', 'A', NULL, 'mcq' FROM topics t WHERE t.topic_code = 'mysql-min-max' AND NOT EXISTS (
  SELECT 1 FROM quiz_questions q WHERE q.topic_id = t.topic_id AND q.question_text = 'What does MAX() return?'
);

INSERT INTO quiz_questions (topic_id, question_text, option_a, option_b, option_c, option_d, correct_option, explanation, question_type)
SELECT t.topic_id, 'What does COUNT(*) return?', 'The total number of rows', 'The sum of all values', 'The average of all values', 'The highest value', 'A', NULL, 'mcq' FROM topics t WHERE t.topic_code = 'mysql-count' AND NOT EXISTS (
  SELECT 1 FROM quiz_questions q WHERE q.topic_id = t.topic_id AND q.question_text = 'What does COUNT(*) return?'
);

INSERT INTO quiz_questions (topic_id, question_text, option_a, option_b, option_c, option_d, correct_option, explanation, question_type)
SELECT t.topic_id, 'What does SUM() do?', 'Calculates the total of a numeric column', 'Counts the number of rows', 'Finds the average', 'Finds the maximum value', 'A', NULL, 'mcq' FROM topics t WHERE t.topic_code = 'mysql-sum' AND NOT EXISTS (
  SELECT 1 FROM quiz_questions q WHERE q.topic_id = t.topic_id AND q.question_text = 'What does SUM() do?'
);

INSERT INTO quiz_questions (topic_id, question_text, option_a, option_b, option_c, option_d, correct_option, explanation, question_type)
SELECT t.topic_id, 'Which function calculates the average?', 'AVG()', 'MEAN()', 'AVERAGE()', 'MEDIAN()', 'A', NULL, 'mcq' FROM topics t WHERE t.topic_code = 'mysql-avg' AND NOT EXISTS (
  SELECT 1 FROM quiz_questions q WHERE q.topic_id = t.topic_id AND q.question_text = 'Which function calculates the average?'
);

INSERT INTO quiz_questions (topic_id, question_text, option_a, option_b, option_c, option_d, correct_option, explanation, question_type)
SELECT t.topic_id, 'What is the LIKE operator used for?', 'Pattern matching in strings', 'Adding two numbers', 'Sorting alphabetically', 'Counting rows', 'A', NULL, 'mcq' FROM topics t WHERE t.topic_code = 'mysql-like' AND NOT EXISTS (
  SELECT 1 FROM quiz_questions q WHERE q.topic_id = t.topic_id AND q.question_text = 'What is the LIKE operator used for?'
);

INSERT INTO quiz_questions (topic_id, question_text, option_a, option_b, option_c, option_d, correct_option, explanation, question_type)
SELECT t.topic_id, 'What does the % wildcard represent?', 'Zero or more characters', 'Exactly one character', 'A single digit', 'A space character', 'A', NULL, 'mcq' FROM topics t WHERE t.topic_code = 'mysql-wildcards' AND NOT EXISTS (
  SELECT 1 FROM quiz_questions q WHERE q.topic_id = t.topic_id AND q.question_text = 'What does the % wildcard represent?'
);

INSERT INTO quiz_questions (topic_id, question_text, option_a, option_b, option_c, option_d, correct_option, explanation, question_type)
SELECT t.topic_id, 'What does the _ wildcard represent?', 'Exactly one character', 'Zero or more characters', 'A number', 'A special character', 'A', NULL, 'mcq' FROM topics t WHERE t.topic_code = 'mysql-wildcards' AND NOT EXISTS (
  SELECT 1 FROM quiz_questions q WHERE q.topic_id = t.topic_id AND q.question_text = 'What does the _ wildcard represent?'
);

INSERT INTO quiz_questions (topic_id, question_text, option_a, option_b, option_c, option_d, correct_option, explanation, question_type)
SELECT t.topic_id, 'What does the IN operator do?', 'Checks if a value matches any value in a list', 'Sorts values in ascending order', 'Joins two tables', 'Creates a new index', 'A', NULL, 'mcq' FROM topics t WHERE t.topic_code = 'mysql-in' AND NOT EXISTS (
  SELECT 1 FROM quiz_questions q WHERE q.topic_id = t.topic_id AND q.question_text = 'What does the IN operator do?'
);

INSERT INTO quiz_questions (topic_id, question_text, option_a, option_b, option_c, option_d, correct_option, explanation, question_type)
SELECT t.topic_id, 'What does BETWEEN do?', 'Selects values within a given range', 'Joins two tables', 'Groups data', 'Sorts results', 'A', NULL, 'mcq' FROM topics t WHERE t.topic_code = 'mysql-between' AND NOT EXISTS (
  SELECT 1 FROM quiz_questions q WHERE q.topic_id = t.topic_id AND q.question_text = 'What does BETWEEN do?'
);

INSERT INTO quiz_questions (topic_id, question_text, option_a, option_b, option_c, option_d, correct_option, explanation, question_type)
SELECT t.topic_id, 'What is an alias in SQL?', 'A temporary name for a table or column', 'A type of database user', 'A foreign key constraint', 'A backup copy of data', 'A', NULL, 'mcq' FROM topics t WHERE t.topic_code = 'mysql-aliases' AND NOT EXISTS (
  SELECT 1 FROM quiz_questions q WHERE q.topic_id = t.topic_id AND q.question_text = 'What is an alias in SQL?'
);

INSERT INTO quiz_questions (topic_id, question_text, option_a, option_b, option_c, option_d, correct_option, explanation, question_type)
SELECT t.topic_id, 'What does a JOIN do?', 'Combines rows from two or more tables', 'Creates a new database', 'Deletes records', 'Sorts data', 'A', NULL, 'mcq' FROM topics t WHERE t.topic_code = 'mysql-joins' AND NOT EXISTS (
  SELECT 1 FROM quiz_questions q WHERE q.topic_id = t.topic_id AND q.question_text = 'What does a JOIN do?'
);

INSERT INTO quiz_questions (topic_id, question_text, option_a, option_b, option_c, option_d, correct_option, explanation, question_type)
SELECT t.topic_id, 'What does INNER JOIN return?', 'Only rows that have matching values in both tables', 'All rows from the left table', 'All rows from both tables', 'Only rows that don''t match', 'A', NULL, 'mcq' FROM topics t WHERE t.topic_code = 'mysql-inner-join' AND NOT EXISTS (
  SELECT 1 FROM quiz_questions q WHERE q.topic_id = t.topic_id AND q.question_text = 'What does INNER JOIN return?'
);

INSERT INTO quiz_questions (topic_id, question_text, option_a, option_b, option_c, option_d, correct_option, explanation, question_type)
SELECT t.topic_id, 'What does LEFT JOIN return?', 'All rows from the left table, plus matching rows from the right', 'Only matching rows from both', 'All rows from the right table', 'Rows that don''t match', 'A', NULL, 'mcq' FROM topics t WHERE t.topic_code = 'mysql-left-join' AND NOT EXISTS (
  SELECT 1 FROM quiz_questions q WHERE q.topic_id = t.topic_id AND q.question_text = 'What does LEFT JOIN return?'
);

INSERT INTO quiz_questions (topic_id, question_text, option_a, option_b, option_c, option_d, correct_option, explanation, question_type)
SELECT t.topic_id, 'What does RIGHT JOIN return?', 'All rows from the right table, plus matching rows from the left', 'Only matching rows from both', 'All rows from the left table', 'Rows that don''t match', 'A', NULL, 'mcq' FROM topics t WHERE t.topic_code = 'mysql-right-join' AND NOT EXISTS (
  SELECT 1 FROM quiz_questions q WHERE q.topic_id = t.topic_id AND q.question_text = 'What does RIGHT JOIN return?'
);

INSERT INTO quiz_questions (topic_id, question_text, option_a, option_b, option_c, option_d, correct_option, explanation, question_type)
SELECT t.topic_id, 'What does CROSS JOIN return?', 'All possible combinations of rows from both tables', 'Only matching rows', 'Only rows from the first table', 'Rows from both tables merged', 'A', NULL, 'mcq' FROM topics t WHERE t.topic_code = 'mysql-cross-join' AND NOT EXISTS (
  SELECT 1 FROM quiz_questions q WHERE q.topic_id = t.topic_id AND q.question_text = 'What does CROSS JOIN return?'
);

INSERT INTO quiz_questions (topic_id, question_text, option_a, option_b, option_c, option_d, correct_option, explanation, question_type)
SELECT t.topic_id, 'What is a SELF JOIN?', 'A table joined with itself', 'A join between two different tables', 'A join with a subquery', 'An automatic join', 'A', NULL, 'mcq' FROM topics t WHERE t.topic_code = 'mysql-self-join' AND NOT EXISTS (
  SELECT 1 FROM quiz_questions q WHERE q.topic_id = t.topic_id AND q.question_text = 'What is a SELF JOIN?'
);

INSERT INTO quiz_questions (topic_id, question_text, option_a, option_b, option_c, option_d, correct_option, explanation, question_type)
SELECT t.topic_id, 'What does UNION do?', 'Combines result sets of two or more SELECT statements', 'Joins two tables horizontally', 'Creates a new database', 'Deletes duplicate rows', 'A', NULL, 'mcq' FROM topics t WHERE t.topic_code = 'mysql-union' AND NOT EXISTS (
  SELECT 1 FROM quiz_questions q WHERE q.topic_id = t.topic_id AND q.question_text = 'What does UNION do?'
);

INSERT INTO quiz_questions (topic_id, question_text, option_a, option_b, option_c, option_d, correct_option, explanation, question_type)
SELECT t.topic_id, 'What does GROUP BY do?', 'Groups rows with the same values into summary rows', 'Sorts the results alphabetically', 'Filters rows based on a condition', 'Joins multiple tables', 'A', NULL, 'mcq' FROM topics t WHERE t.topic_code = 'mysql-group-by' AND NOT EXISTS (
  SELECT 1 FROM quiz_questions q WHERE q.topic_id = t.topic_id AND q.question_text = 'What does GROUP BY do?'
);

INSERT INTO quiz_questions (topic_id, question_text, option_a, option_b, option_c, option_d, correct_option, explanation, question_type)
SELECT t.topic_id, 'What is the difference between WHERE and HAVING?', 'WHERE filters rows before grouping, HAVING filters after', 'There is no difference', 'WHERE is faster', 'HAVING can only be used with COUNT', 'A', NULL, 'mcq' FROM topics t WHERE t.topic_code = 'mysql-having' AND NOT EXISTS (
  SELECT 1 FROM quiz_questions q WHERE q.topic_id = t.topic_id AND q.question_text = 'What is the difference between WHERE and HAVING?'
);

INSERT INTO quiz_questions (topic_id, question_text, option_a, option_b, option_c, option_d, correct_option, explanation, question_type)
SELECT t.topic_id, 'What does EXISTS check?', 'Whether a subquery returns any rows', 'If a table exists', 'If a column exists', 'If a database exists', 'A', NULL, 'mcq' FROM topics t WHERE t.topic_code = 'mysql-exists' AND NOT EXISTS (
  SELECT 1 FROM quiz_questions q WHERE q.topic_id = t.topic_id AND q.question_text = 'What does EXISTS check?'
);

INSERT INTO quiz_questions (topic_id, question_text, option_a, option_b, option_c, option_d, correct_option, explanation, question_type)
SELECT t.topic_id, 'Which statement creates a new database?', 'CREATE DATABASE', 'MAKE DATABASE', 'NEW DATABASE', 'ADD DATABASE', 'A', NULL, 'mcq' FROM topics t WHERE t.topic_code = 'mysql-create-db' AND NOT EXISTS (
  SELECT 1 FROM quiz_questions q WHERE q.topic_id = t.topic_id AND q.question_text = 'Which statement creates a new database?'
);

INSERT INTO quiz_questions (topic_id, question_text, option_a, option_b, option_c, option_d, correct_option, explanation, question_type)
SELECT t.topic_id, 'Which statement deletes a database?', 'DROP DATABASE', 'DELETE DATABASE', 'REMOVE DATABASE', 'CLEAR DATABASE', 'A', NULL, 'mcq' FROM topics t WHERE t.topic_code = 'mysql-drop-db' AND NOT EXISTS (
  SELECT 1 FROM quiz_questions q WHERE q.topic_id = t.topic_id AND q.question_text = 'Which statement deletes a database?'
);

INSERT INTO quiz_questions (topic_id, question_text, option_a, option_b, option_c, option_d, correct_option, explanation, question_type)
SELECT t.topic_id, 'Which statement creates a new table?', 'CREATE TABLE', 'MAKE TABLE', 'NEW TABLE', 'ADD TABLE', 'A', NULL, 'mcq' FROM topics t WHERE t.topic_code = 'mysql-create-table' AND NOT EXISTS (
  SELECT 1 FROM quiz_questions q WHERE q.topic_id = t.topic_id AND q.question_text = 'Which statement creates a new table?'
);

INSERT INTO quiz_questions (topic_id, question_text, option_a, option_b, option_c, option_d, correct_option, explanation, question_type)
SELECT t.topic_id, 'Which constraint ensures a column cannot have NULL values?', 'NOT NULL', 'NO EMPTY', 'REQUIRED', 'MANDATORY', 'A', NULL, 'mcq' FROM topics t WHERE t.topic_code = 'mysql-create-table' AND NOT EXISTS (
  SELECT 1 FROM quiz_questions q WHERE q.topic_id = t.topic_id AND q.question_text = 'Which constraint ensures a column cannot have NULL values?'
);

INSERT INTO quiz_questions (topic_id, question_text, option_a, option_b, option_c, option_d, correct_option, explanation, question_type)
SELECT t.topic_id, 'Which statement deletes a table?', 'DROP TABLE', 'DELETE TABLE', 'REMOVE TABLE', 'CLEAR TABLE', 'A', NULL, 'mcq' FROM topics t WHERE t.topic_code = 'mysql-drop-table' AND NOT EXISTS (
  SELECT 1 FROM quiz_questions q WHERE q.topic_id = t.topic_id AND q.question_text = 'Which statement deletes a table?'
);

INSERT INTO quiz_questions (topic_id, question_text, option_a, option_b, option_c, option_d, correct_option, explanation, question_type)
SELECT t.topic_id, 'What does ALTER TABLE do?', 'Modifies an existing table structure', 'Creates a new table', 'Deletes a table', 'Renames the database', 'A', NULL, 'mcq' FROM topics t WHERE t.topic_code = 'mysql-alter-table' AND NOT EXISTS (
  SELECT 1 FROM quiz_questions q WHERE q.topic_id = t.topic_id AND q.question_text = 'What does ALTER TABLE do?'
);

INSERT INTO quiz_questions (topic_id, question_text, option_a, option_b, option_c, option_d, correct_option, explanation, question_type)
SELECT t.topic_id, 'What are constraints?', 'Rules enforced on data columns', 'Table relationships', 'Query conditions', 'Index types', 'A', NULL, 'mcq' FROM topics t WHERE t.topic_code = 'mysql-constraints' AND NOT EXISTS (
  SELECT 1 FROM quiz_questions q WHERE q.topic_id = t.topic_id AND q.question_text = 'What are constraints?'
);

INSERT INTO quiz_questions (topic_id, question_text, option_a, option_b, option_c, option_d, correct_option, explanation, question_type)
SELECT t.topic_id, 'What does NOT NULL ensure?', 'A column must always have a value', 'A column can be empty', 'A column must be unique', 'A column must be a number', 'A', NULL, 'mcq' FROM topics t WHERE t.topic_code = 'mysql-not-null' AND NOT EXISTS (
  SELECT 1 FROM quiz_questions q WHERE q.topic_id = t.topic_id AND q.question_text = 'What does NOT NULL ensure?'
);

INSERT INTO quiz_questions (topic_id, question_text, option_a, option_b, option_c, option_d, correct_option, explanation, question_type)
SELECT t.topic_id, 'What does UNIQUE ensure?', 'All values in a column are different', 'A column cannot be NULL', 'A column must be a number', 'A column must be indexed', 'A', NULL, 'mcq' FROM topics t WHERE t.topic_code = 'mysql-unique' AND NOT EXISTS (
  SELECT 1 FROM quiz_questions q WHERE q.topic_id = t.topic_id AND q.question_text = 'What does UNIQUE ensure?'
);

INSERT INTO quiz_questions (topic_id, question_text, option_a, option_b, option_c, option_d, correct_option, explanation, question_type)
SELECT t.topic_id, 'What is a PRIMARY KEY?', 'A unique identifier for each record', 'A column that can have duplicates', 'A foreign key reference', 'An index on multiple columns', 'A', NULL, 'mcq' FROM topics t WHERE t.topic_code = 'mysql-primary-key' AND NOT EXISTS (
  SELECT 1 FROM quiz_questions q WHERE q.topic_id = t.topic_id AND q.question_text = 'What is a PRIMARY KEY?'
);

INSERT INTO quiz_questions (topic_id, question_text, option_a, option_b, option_c, option_d, correct_option, explanation, question_type)
SELECT t.topic_id, 'What is a FOREIGN KEY?', 'A key that links two tables together', 'A primary key in another table', 'A unique constraint', 'An auto-increment column', 'A', NULL, 'mcq' FROM topics t WHERE t.topic_code = 'mysql-foreign-key' AND NOT EXISTS (
  SELECT 1 FROM quiz_questions q WHERE q.topic_id = t.topic_id AND q.question_text = 'What is a FOREIGN KEY?'
);

INSERT INTO quiz_questions (topic_id, question_text, option_a, option_b, option_c, option_d, correct_option, explanation, question_type)
SELECT t.topic_id, 'What does CHECK constraint do?', 'Ensures all values satisfy a specific condition', 'Checks if table exists', 'Checks data types', 'Checks for NULL values', 'A', NULL, 'mcq' FROM topics t WHERE t.topic_code = 'mysql-check' AND NOT EXISTS (
  SELECT 1 FROM quiz_questions q WHERE q.topic_id = t.topic_id AND q.question_text = 'What does CHECK constraint do?'
);

INSERT INTO quiz_questions (topic_id, question_text, option_a, option_b, option_c, option_d, correct_option, explanation, question_type)
SELECT t.topic_id, 'What does DEFAULT do?', 'Sets a default value for a column', 'Deletes default constraints', 'Checks default values', 'Sets the primary key', 'A', NULL, 'mcq' FROM topics t WHERE t.topic_code = 'mysql-default' AND NOT EXISTS (
  SELECT 1 FROM quiz_questions q WHERE q.topic_id = t.topic_id AND q.question_text = 'What does DEFAULT do?'
);

INSERT INTO quiz_questions (topic_id, question_text, option_a, option_b, option_c, option_d, correct_option, explanation, question_type)
SELECT t.topic_id, 'What is the purpose of an index?', 'To speed up data retrieval', 'To store more data', 'To encrypt the database', 'To delete old records', 'A', NULL, 'mcq' FROM topics t WHERE t.topic_code = 'mysql-create-index' AND NOT EXISTS (
  SELECT 1 FROM quiz_questions q WHERE q.topic_id = t.topic_id AND q.question_text = 'What is the purpose of an index?'
);

INSERT INTO quiz_questions (topic_id, question_text, option_a, option_b, option_c, option_d, correct_option, explanation, question_type)
SELECT t.topic_id, 'What does AUTO_INCREMENT do?', 'Generates a unique number automatically for new records', 'Increases table size automatically', 'Updates records automatically', 'Creates backups automatically', 'A', NULL, 'mcq' FROM topics t WHERE t.topic_code = 'mysql-auto-increment' AND NOT EXISTS (
  SELECT 1 FROM quiz_questions q WHERE q.topic_id = t.topic_id AND q.question_text = 'What does AUTO_INCREMENT do?'
);

INSERT INTO quiz_questions (topic_id, question_text, option_a, option_b, option_c, option_d, correct_option, explanation, question_type)
SELECT t.topic_id, 'Which data type stores both date and time?', 'DATETIME', 'DATE', 'TIME', 'YEAR', 'A', NULL, 'mcq' FROM topics t WHERE t.topic_code = 'mysql-dates' AND NOT EXISTS (
  SELECT 1 FROM quiz_questions q WHERE q.topic_id = t.topic_id AND q.question_text = 'Which data type stores both date and time?'
);

INSERT INTO quiz_questions (topic_id, question_text, option_a, option_b, option_c, option_d, correct_option, explanation, question_type)
SELECT t.topic_id, 'What is a VIEW?', 'A virtual table based on a query', 'A physical table copy', 'A database backup', 'A type of index', 'A', NULL, 'mcq' FROM topics t WHERE t.topic_code = 'mysql-views' AND NOT EXISTS (
  SELECT 1 FROM quiz_questions q WHERE q.topic_id = t.topic_id AND q.question_text = 'What is a VIEW?'
);
